# Generated by Django 5.0.3 on 2024-04-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price_type',
            field=models.CharField(choices=[('$', '$'), ('Sum', 'Sum')], default='Sum', max_length=10),
        ),
    ]
